import Link from "next/link";
import { getPanelContext } from "@/lib/panel-context";
import { PanelDrawer } from "../../components/panel-drawer";
import { issueContractLink, updateContract, markContractStatus, deleteContract } from "../sales-actions";
import { ConfirmDeleteButton } from "../../accounts/confirm-delete-button";
import { CrmTabs } from "../crm-tabs";
import "../crm.css";

type Props={searchParams:Promise<{search?:string;status?:string;share?:string}>};
type Contract={id:string;contract_no:string;title:string;scope:string|null;amount:number;currency:string;payment_plan:string|null;start_date:string|null;due_date:string|null;status:string;sent_at:string|null;first_viewed_at:string|null;last_viewed_at:string|null;view_count:number;signed_name:string|null;signed_at:string|null;workflow_id:string|null;created_at:string;customer_address:string|null;customer_tax_number:string|null;customer_tax_office:string|null;opportunity_id:string;crm_opportunities:{id:string;customer_name:string;contact_email:string|null;contact_phone:string|null;title:string;request_details:Record<string,unknown>|null}|null};
const statuses=["draft","sent","signed","rejected","cancelled","completed"];
const labels:Record<string,string>={draft:"Taslak",sent:"İmza bekliyor",signed:"İmzalandı",rejected:"Reddedildi",cancelled:"İptal",completed:"Tamamlandı"};
const money=(v:number,c:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c}).format(v/100);
const dateTime=(v:string|null)=>v?new Date(v).toLocaleString("tr-TR"):"—";
export default async function ContractsPage({searchParams}:Props){
 const p=await searchParams; const search=(p.search??"").trim(); const status=statuses.includes(p.status??"")?p.status!:""; const share=p.share??"";
 const {supabase,membership,modules}=await getPanelContext(); if(!modules.some(m=>m.code==="crm")) throw new Error("CRM modülüne erişiminiz yok.");
 let q=supabase.from("crm_contracts").select("id,contract_no,title,scope,amount,currency,payment_plan,start_date,due_date,status,sent_at,first_viewed_at,last_viewed_at,view_count,signed_name,signed_at,workflow_id,created_at,customer_address,customer_tax_number,customer_tax_office,opportunity_id,crm_opportunities!inner(id,customer_name,contact_email,contact_phone,title,request_details)").eq("organization_id",membership.organization_id);
 if(status) q=q.eq("status",status); if(search) q=q.or(`contract_no.ilike.%${search}%,title.ilike.%${search}%`);
 const {data,error}=await q.order("created_at",{ascending:false}); if(error) throw new Error("Sözleşmeler okunamadı: "+error.message); const rows=(data??[]) as unknown as Contract[];
 const shareUrl=share?`https://app.arvo-os.com/sozlesme/${share}`:""; const total=rows.reduce((s,r)=>s+Number(r.amount),0);
 return <div className="crm-page-stack"><div className="panel-pagehead"><div><small className="panel-kicker">CRM / SÖZLEŞMELER</small><h1>Sözleşmeler</h1><p>Tekliften oluşan sözleşmeleri kontrol edin, imzaya gönderin ve oluşan iş akışını takip edin.</p></div><div className="panel-page-actions"><span className="status-pill">{rows.length} kayıt</span><Link className="panel-primary" href="/panel/crm/proposals">Tekliflere git</Link></div></div><CrmTabs active="sozlesmeler" /><div className="module-tab-panel">
 {shareUrl?<section className="panel-card"><small className="panel-kicker">İMZA BAĞLANTISI HAZIR</small><h2>Sözleşme bağlantısı</h2><p style={{wordBreak:"break-all"}}>{shareUrl}</p><div className="panel-page-actions"><a className="panel-primary" href={`mailto:?subject=Sözleşmeniz&body=${encodeURIComponent("Sözleşmenizi inceleyip imzalamak için: "+shareUrl)}`}>E-posta ile gönder</a><a className="panel-secondary" target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent("Sözleşmenizi inceleyip imzalamak için: "+shareUrl)}`}>WhatsApp ile gönder</a><a className="panel-secondary" target="_blank" rel="noreferrer" href={shareUrl}>Önizle</a></div></section>:null}
 <section className="crm-metrics"><article><small>TOPLAM</small><strong>{rows.length}</strong><span>Sözleşme kaydı</span></article><article><small>TOPLAM DEĞER</small><strong>{money(total,"TRY")}</strong><span>Sözleşme bedeli</span></article><article><small>GÖRÜNTÜLENEN</small><strong>{rows.filter(r=>r.view_count>0).length}</strong><span>Müşteri tarafından açılan</span></article><article><small>İMZALANAN</small><strong>{rows.filter(r=>r.status==="signed").length}</strong><span>İş akışı oluşturulan</span></article></section>
 <section className="panel-card"><form method="get" className="crm-filter-form"><label><span>Sözleşme / müşteri ara</span><input name="search" defaultValue={search}/></label><label><span>Durum</span><select name="status" defaultValue={status}><option value="">Tümü</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><div><button className="panel-primary">Filtrele</button><Link className="panel-secondary" href="/panel/crm/contracts">Temizle</Link></div></form></section>
 {rows.length?<section className="panel-card crm-table-wrap"><table className="crm-data-table"><thead><tr><th>Sözleşme No</th><th>Müşteri</th><th>Konu</th><th>Tutar</th><th>Durum</th><th>Teslim</th><th></th></tr></thead><tbody>{rows.map(row=>{const customer=row.crm_opportunities;const edit=<form className="panel-form" action={updateContract}><input type="hidden" name="contract_id" value={row.id}/><input type="hidden" name="opportunity_id" value={customer?.id??""}/><input type="hidden" name="current_details" value={JSON.stringify(customer?.request_details??{})}/><p className="wide panel-form-note">Müşteri / Talep Bilgileri</p><label>Müşteri adı<input name="customer_name" defaultValue={customer?.customer_name??""}/></label><label>Telefon<input name="contact_phone" defaultValue={customer?.contact_phone??""}/></label><label>E-posta<input name="contact_email" defaultValue={customer?.contact_email??""}/></label><label>Hizmet türü<input name="service_type" defaultValue={String(customer?.request_details?.service_type??"")}/></label><label>Akademik seviye<input name="academic_level" defaultValue={String(customer?.request_details?.academic_level??"")}/></label><label>Üniversite<input name="university" defaultValue={String(customer?.request_details?.university??"")}/></label><label>Bölüm<input name="department" defaultValue={String(customer?.request_details?.department??"")}/></label><p className="wide panel-form-note">Sözleşme Bilgileri</p><label>Başlık<input name="title" defaultValue={row.title} required/></label><label>Tutar<input name="amount" type="number" step="0.01" min="0" defaultValue={(row.amount/100).toFixed(2)} required/></label><label className="wide">Kapsam<textarea name="scope" defaultValue={row.scope??""} required/></label><label>Ödeme planı<input name="payment_plan" defaultValue={row.payment_plan??""}/></label><label>Başlangıç<input name="start_date" type="date" defaultValue={row.start_date??""}/></label><label>Teslim<input name="due_date" type="date" defaultValue={row.due_date??""}/></label><label className="wide">Adres <small style={{fontWeight:400,color:"var(--muted)"}}>(kurumsal müşteri için)</small><input name="customer_address" defaultValue={row.customer_address??""} placeholder="Fatura/sözleşme adresi"/></label><label>Vergi numarası<input name="customer_tax_number" defaultValue={row.customer_tax_number??""} placeholder="VKN / TCKN"/></label><label>Vergi dairesi<input name="customer_tax_office" defaultValue={row.customer_tax_office??""}/></label><div className="wide panel-form-actions"><button className="panel-primary">Kaydet</button></div></form>;
 const detail=<div className="crm-request-preview"><span>{labels[row.status]??row.status}</span><h3>{customer?.customer_name}</h3><h4>{row.title}</h4><dl><div><dt>Telefon</dt><dd>{customer?.contact_phone||"Belirtilmedi"}</dd></div><div><dt>E-posta</dt><dd>{customer?.contact_email||"Belirtilmedi"}</dd></div><div><dt>Ödeme planı</dt><dd>{row.payment_plan||"Belirtilmedi"}</dd></div><div><dt>İmzalayan</dt><dd>{row.signed_name||"Bekleniyor"}</dd></div></dl>{row.scope?<p>{row.scope}</p>:null}<div className="crm-document-timeline"><span><b>Oluşturuldu</b>{dateTime(row.created_at)}</span><span><b>İmzaya gönderildi</b>{dateTime(row.sent_at)}</span><span><b>İlk görüntüleme</b>{dateTime(row.first_viewed_at)}</span><span><b>Son görüntüleme</b>{dateTime(row.last_viewed_at)}</span><span><b>Açılma</b>{row.view_count} kez</span><span><b>İmza</b>{row.signed_at?dateTime(row.signed_at):"Bekleniyor"}</span></div></div>;
 return <tr key={row.id}>
        <td className="crm-table-mono">{row.contract_no}</td>
        <td><span className="crm-table-title">{customer?.customer_name}</span><span className="crm-table-sub">{customer?.contact_phone||customer?.contact_email||"İletişim yok"}</span></td>
        <td>{row.title}</td>
        <td>{money(row.amount,row.currency)}</td>
        <td><span className="status-pill">{labels[row.status]??row.status}</span></td>
        <td>{row.due_date?new Date(row.due_date+"T00:00:00").toLocaleDateString("tr-TR"):"—"}</td>
        <td className="crm-table-actions">
          <PanelDrawer triggerLabel="Önizle" title={row.contract_no}>{detail}</PanelDrawer>
          {!["signed","completed","cancelled"].includes(row.status)?<><PanelDrawer triggerLabel="Düzenle" title={row.contract_no} description="Sözleşme bilgilerini kontrol edin.">{edit}</PanelDrawer><form action={issueContractLink}><input type="hidden" name="contract_id" value={row.id}/><button className="panel-primary">İmzaya gönder</button></form></>:null}
          {row.workflow_id?<Link className="panel-secondary" href="/panel/operations">İş akışı</Link>:null}
          {!["signed","completed","rejected","cancelled"].includes(row.status)?<form action={markContractStatus}><input type="hidden" name="contract_id" value={row.id}/><input type="hidden" name="status" value="rejected"/><button className="panel-secondary">Reddedildi</button></form>:null}
          {!["signed","completed","rejected","cancelled"].includes(row.status)?<form action={markContractStatus}><input type="hidden" name="contract_id" value={row.id}/><input type="hidden" name="status" value="cancelled"/><button className="panel-secondary">İptal</button></form>:null}
          <form action={deleteContract}><input type="hidden" name="contract_id" value={row.id}/><ConfirmDeleteButton label="Sil" confirmMessage={`${row.contract_no} sözleşmesini kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.`}/></form>
        </td>
      </tr>})}</tbody></table></section>:<div className="panel-card crm-empty">Sözleşme bulunamadı.</div>}</div></div>;
}
