import Link from "next/link";
import { getPanelContext } from "@/lib/panel-context";
import { PanelDrawer } from "../../components/panel-drawer";
import { createProposalRevision, issueProposalLink, updateProposal } from "../sales-actions";
import "../crm.css";

type Props={searchParams:Promise<{search?:string;status?:string;share?:string}>};
type Proposal={id:string;proposal_no:string;title:string;scope:string|null;amount:number;currency:string;payment_plan:string|null;valid_until:string|null;status:string;sent_at:string|null;first_viewed_at:string|null;last_viewed_at:string|null;view_count:number;responded_at:string|null;created_at:string;root_proposal_id:string|null;previous_revision_id:string|null;revision_no:number;revision_note:string|null;superseded_at:string|null;superseded_by:string|null;crm_opportunities:{customer_name:string;contact_email:string|null;contact_phone:string|null;title:string}|null};
const statuses=["draft","sent","accepted","rejected","expired","archived"];
const labels:Record<string,string>={draft:"Taslak",sent:"Gönderildi",accepted:"Kabul edildi",rejected:"Reddedildi",expired:"Süresi doldu",archived:"Arşiv"};
const money=(v:number,c:string)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c}).format(v/100);
const dateTime=(v:string|null)=>v?new Date(v).toLocaleString("tr-TR"):"—";
export default async function ProposalsPage({searchParams}:Props){
 const p=await searchParams;const search=(p.search??"").trim();const status=statuses.includes(p.status??"")?p.status!:"";const share=p.share??"";
 const {supabase,membership,modules}=await getPanelContext();if(!modules.some(m=>m.code==="crm"))throw new Error("CRM modülüne erişiminiz yok.");
 let q=supabase.from("crm_proposals").select("id,proposal_no,title,scope,amount,currency,payment_plan,valid_until,status,sent_at,first_viewed_at,last_viewed_at,view_count,responded_at,created_at,root_proposal_id,previous_revision_id,revision_no,revision_note,superseded_at,superseded_by,crm_opportunities!inner(customer_name,contact_email,contact_phone,title)").eq("organization_id",membership.organization_id);
 if(status)q=q.eq("status",status);if(search)q=q.or(`proposal_no.ilike.%${search}%,title.ilike.%${search}%`);
 const {data,error}=await q.order("created_at",{ascending:false});if(error)throw new Error("Teklifler okunamadı: "+error.message);const rows=(data??[]) as unknown as Proposal[];
 const shareUrl=share?`https://app.arvo-os.com/teklif/${share}`:"";const total=rows.reduce((s,r)=>s+Number(r.amount),0);
 const revisionCount=rows.filter(r=>r.revision_no>0).length;
 return <div className="crm-page-stack"><div className="panel-pagehead"><div><small className="panel-kicker">CRM / TEKLİFLER</small><h1>Teklifler</h1><p>Teklifleri düzenleyin, revize edin, müşteriye gönderin ve karar durumunu takip edin.</p></div><div className="panel-page-actions"><span className="status-pill">{rows.length} kayıt</span><Link className="panel-primary" href="/panel/crm">Taleplere git</Link></div></div>
 {shareUrl?<section className="panel-card"><small className="panel-kicker">PAYLAŞIM BAĞLANTISI HAZIR</small><h2>Teklif bağlantısı</h2><p style={{wordBreak:"break-all"}}>{shareUrl}</p><div className="panel-page-actions"><a className="panel-primary" href={`mailto:?subject=Teklifiniz&body=${encodeURIComponent("Teklifinizi incelemek için: "+shareUrl)}`}>E-posta ile gönder</a><a className="panel-secondary" target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent("Teklifinizi incelemek için: "+shareUrl)}`}>WhatsApp ile gönder</a><a className="panel-secondary" target="_blank" rel="noreferrer" href={shareUrl}>Önizle</a></div></section>:null}
 <section className="crm-metrics"><article><small>TOPLAM</small><strong>{rows.length}</strong><span>Teklif kaydı</span></article><article><small>TOPLAM DEĞER</small><strong>{money(total,"TRY")}</strong><span>Teklif bedeli</span></article><article><small>REVİZYON</small><strong>{revisionCount}</strong><span>Oluşturulan yeni sürüm</span></article><article><small>KABUL</small><strong>{rows.filter(r=>r.status==="accepted").length}</strong><span>Sözleşmeye aktarılan</span></article></section>
 <section className="panel-card"><form method="get" className="crm-filter-form"><label><span>Teklif / müşteri ara</span><input name="search" defaultValue={search}/></label><label><span>Durum</span><select name="status" defaultValue={status}><option value="">Tümü</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><div><button className="panel-primary">Filtrele</button><Link className="panel-secondary" href="/panel/crm/proposals">Temizle</Link></div></form></section>
 <section className="crm-record-list">{rows.map(row=>{const customer=row.crm_opportunities;const superseded=Boolean(row.superseded_by);const locked=["accepted","rejected","archived"].includes(row.status)||superseded;const edit=<form className="panel-form" action={updateProposal}><input type="hidden" name="proposal_id" value={row.id}/><label>Başlık<input name="title" defaultValue={row.title} required/></label><label>Tutar<input name="amount" type="number" step="0.01" min="0" defaultValue={(row.amount/100).toFixed(2)} required/></label><label className="wide">Kapsam<textarea name="scope" defaultValue={row.scope??""} required/></label><label>Ödeme planı<input name="payment_plan" defaultValue={row.payment_plan??""}/></label><label>Geçerlilik<input name="valid_until" type="date" defaultValue={row.valid_until??""}/></label><div className="wide panel-form-actions"><button className="panel-primary">Kaydet</button></div></form>;
 const revision=<form className="panel-form" action={createProposalRevision}><input type="hidden" name="proposal_id" value={row.id}/><label className="wide">Revizyon nedeni<textarea name="revision_reason" required minLength={3} maxLength={1000} placeholder="Müşterinin talebi, kapsam değişikliği, fiyat güncellemesi..."/></label><div className="wide panel-card" style={{padding:14}}><strong>Yeni revizyon: {row.proposal_no.replace(/-R\d+$/,"")}-R{row.revision_no+1}</strong><p style={{margin:"8px 0 0"}}>Mevcut sürüm arşivlenecek ve müşterinin yalnızca yeni sürümü onaylamasına izin verilecek.</p></div><div className="wide panel-form-actions"><button className="panel-primary">Revizyonu Oluştur</button></div></form>;
 return <article className="panel-card crm-record" key={row.id}><div className="crm-record-main"><div className="crm-record-heading"><span className="crm-record-number">{row.proposal_no}</span><span className="status-pill">{superseded?"Eski revizyon":labels[row.status]??row.status}</span>{row.revision_no>0?<span className="status-pill">R{row.revision_no}</span>:null}</div><h2>{customer?.customer_name}</h2><h3>{row.title}</h3><div className="crm-record-meta"><span>{customer?.contact_phone||"Telefon yok"}</span><span>{customer?.contact_email||"E-posta yok"}</span><span>{row.valid_until?`Geçerli: ${new Date(row.valid_until+"T00:00:00").toLocaleDateString("tr-TR")}`:"Süre yok"}</span></div><p>{row.scope}</p>{row.revision_note?<p><b>Revizyon nedeni:</b> {row.revision_note}</p>:null}{superseded?<p><b>Bu sürüm daha yeni bir revizyonla değiştirilmiştir.</b> Salt okunur olarak korunur.</p>:null}<div className="crm-document-timeline"><span><b>Oluşturuldu</b>{dateTime(row.created_at)}</span><span><b>Gönderildi</b>{dateTime(row.sent_at)}</span><span><b>İlk görüntüleme</b>{dateTime(row.first_viewed_at)}</span><span><b>Son görüntüleme</b>{dateTime(row.last_viewed_at)}</span><span><b>Açılma</b>{row.view_count} kez</span><span><b>Revizyon</b>{row.revision_no?`R${row.revision_no}`:"İlk sürüm"}</span></div><div className="panel-page-actions">{!locked?<PanelDrawer triggerLabel="Düzenle" title={row.proposal_no} description="Teklif bilgilerini kontrol edin.">{edit}</PanelDrawer>:null}{!locked?<PanelDrawer triggerLabel="Revizyon Oluştur" title={`${row.proposal_no} revizyonu`} description="Yeni sürüm oluşturun; mevcut teklif arşivlenecektir.">{revision}</PanelDrawer>:null}{!locked?<form action={issueProposalLink}><input type="hidden" name="proposal_id" value={row.id}/><button className="panel-primary">Link oluştur / yenile</button></form>:null}</div></div><aside className="crm-record-side"><small>TEKLİF BEDELİ</small><strong>{money(row.amount,row.currency)}</strong><span>{row.payment_plan||"Ödeme planı belirtilmedi"}</span></aside></article>})}{!rows.length?<div className="panel-card crm-empty">Teklif bulunamadı.</div>:null}</section></div>;
}
